### ISSUE TITLE
Spawn on join not working

### ISSUE THREAD

**Issue by rowdyslav** [CalRL/Hubbly#22]
not teleporting on spawn, simple as that

Purpur 1.21.1

```
spawn:
  world: world
  x: 78.5
  y: 162.0
  z: -40.5
  # YAW AND PITCH WILL ROUND TO {-135, -90, -45, 0, 45, 90, 135} WHEN YOU USE /SETSPAWN, YOU CAN MANUALLY OVERRIDE THIS HERE
  yaw: 0.0
  pitch: 0.0


# -----------------#
# PLAYER SETTINGS #
# -----------------#


player:
  spawn_on_join: true
```
